### PR TITLE
you should delete this shit and use backbone instead

### PR DESCRIPTION
**Pull request by weslleyaraujo**
First time i saw dronejs

img

### CODE REVIEW

**Comment by persocon** [comment]
+1

**Comment by stehzitcha** [comment]
+1

**Comment by guilhermepontes** [comment]
+1

**Comment by enzotoshio** [comment]
+1

**Comment by mauriciosoares** [comment]
+1

**Comment by enzotoshio** [comment]
for(; drone === shit ;) {
  document.write("+1");
}

**Comment by tcione** [comment]
+1

**Comment by thiagofm** [comment]
:+1: 

worse than IE

**Comment by tcelestino** [comment]
+10

**Comment by raulmangolin** [comment]
+1

**Comment by rafaeldff** [comment]
Ah, R7. Image

**Comment by persocon** [comment]
+1

**Comment by enzotoshio** [comment]
+1

**Pull request closed without merging**
