### PR TITLE
you should delete this shit and use backbone instead

### PR DESCRIPTION
**Pull request by guilhermepontes**
fixing your shit

### CODE REVIEW

**Comment by weslleyaraujo** [comment]
+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1

**Comment by persocon** [comment]
+1

**Comment by enzotoshio** [comment]
+1

**Comment by thiagofm** [comment]
:+1: :shipit:

**Comment by tcione** [comment]
+1

**Comment by stehzitcha** [comment]
+1

**Comment by thiagofm** [comment]
such noob

ps: eu sei que é much shit, mas é que tá ruim mermo

**Comment by persocon** [comment]
+1

**Comment by enzotoshio** [comment]
+1

**Comment by rafaelsachetto** [comment]
+1

**Comment by guilhermehn** [comment]
+1

**Pull request closed without merging**
